language: python
env:
    global:
        - OMP_NUM_THREADS=4
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
script: 
    - pytest --cov=fgivenx
after_success: 
    - codecov
