language: python
env:
    global:
        - OMP_NUM_THREADS=4
python:
    - "2.7"
    - "3.6"
install:
    - pip install -r requirements.txt
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
script: 
    - pytest --cov=fgivenx
after_success: 
    - codecov
